### PR TITLE
Adding TS typings, removing Buffer deprecated warning, add npmignore and improving docs.

### PR DESCRIPTION
**Pull request by Fazendaaa**
Hey, @connrs . Thanks for this awesome package!

Due to Hacktoberfest 2018, I'm contributing to some packages that I use; yours is one of those.

TypeScript typings help a lot of us who use it due to it's integration to TSLint and some more strict checkings, needed to be performed in some cases in the used packages as well; that's why I've decided to share the ones that I've made, making it more accessible to all that programs in this environment :)

* [x] I did change some of your code, but only to remove a deprecated warning, no new test was added.
* [x] Travis config was changed to support those tests.
* [x] Documentation modified to add code highlight.
* [x] Added a .npmignore file.

### CODE REVIEW

**Comment by connrs** [comment]
Hey @Fazendaaa,

I'm always blown away when it turns out someone's using something I've built! Thanks for the commits here.

I'm away from my 'open source desk' at the moment but I will definitely merge this (and publish) over the weekend.

**Comment by Fazendaaa** [comment]
@connrs , I was thinking... Can I rewrite this package in TS?

I intend to address the #2 issue and write integrate with TypeDOC

**Comment by connrs** [comment]
Why not! Go for it and when it's done I'll publish

**Comment by Fazendaaa** [comment]
@connrs, I have finished the rewriting, adding the enhancement mentioned in #2 and other things since my last PR.

* [x] API documentation trough TypeDocs, which means a Github Pages shows how to use it
* [x] Git hooks trough Husky, assuring a standard development to this package
* [x] README badges
* [x] Linter patterns from Microsoft -- which I personally think they are the best
* [x] Webpack configuration, adding a tool of future proofing this package, allowing new features to be easily configured since the prerogative do it so is already there
* [x] Codecov pipe, adding a coverage from testing done after ever PR
* [x] Synk integration, this package is "zero dependency" but if someday any is added, it will verify for "leaking" like bugs or even possible security breaches.
* [x] Codeclimate analysis like code duplication, complexity and other too many things to name it ahahaha

That being said, thanks again for allowing me to do this :)

**note**: all of those systems must be added, if you ran into any issues adding them, tell me that I will help you out; also, all of those are free to open source project.

**Comment by connrs** [comment]
Thanks for all the contributions here! I'll put some time aside tomorrow to publishing it. If I have any problems I'll be in touch!

**Comment by connrs** [comment]
Hi @Fazendaaa I'm just getting ready to publish 2.0.0 and I'd like to update the package.json to include you as a contributor. I don't want to put anything in there that's private so would you be comfortable with me putting this in the contributors field?

    {
        "name": "Fazendaaa",
        "url": "http://fazendaaa.me/"
    }

I can't see your email address when not logged in to GitHub so I've left that out.

**Comment by Fazendaaa** [comment]
@connrs Thanks you, and my e-mail is: `lucas.carotta@outlook.com`

**Pull request merged**
